services:
    web:
        build: .
        container_name: web
        image: php:8.2-apache
        volumes:
            - .:/var/www/html
        ports:
            - '8888:80'
        networks:
            - app

    mysql:
        image: mysql
        container_name: mysql
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3307:3306
        networks:
            - app

    # redis:
    #     image: redis
    #     container_name: redis
    #     volumes:
    #         - redis:/data
    #     ports:
    #         - 6380:6379
    #     networks:
    #         - app

    # mongo:
    #     image: mongo
    #     container_name: mongo
    #     volumes:
    #         - mongo:/data/db
    #     ports:
    #         - 6380:6379
    #     networks:
    #         - app

volumes:
    mysql:
    # redis:
    # mongo:

networks:
    app:
      driver: bridge